version: '2'
services:
  neo4j:
    image: 'docker.io/bitnami/neo4j:4-debian-10'
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - '/mnt/volume_nyc1_01/neo4j:/bitnami'
    environment:
      - NEO4J_HOST=localhost
    restart: always
  neo4j-ron:
    image: 'docker.io/bitnami/neo4j:4-debian-10'
    ports:
      - '17474:7474'
      - '17473:7473'
      - '17687:7687'
    volumes:
      - '/mnt/volume_nyc1_01/neo4j-ron:/bitnami'
    environment:
      - NEO4J_HOST=localhost
    restart: always
  neo4j-kevin:
    image: 'docker.io/bitnami/neo4j:4-debian-10'
    ports:
      - '8474:7474'
      - '8473:7473'
      - '8687:7687'
    volumes:
      - '/mnt/volume_nyc1_01/neo4j-kevin:/bitnami'
    environment:
      - NEO4J_HOST=localhost
    restart: always
  neo4j-jonathan:
    image: 'docker.io/bitnami/neo4j:4-debian-10'
    ports:
      - '18474:7474'
      - '18473:7473'
      - '18687:7687'
    volumes:
      - '/mnt/volume_nyc1_01/neo4j-jonathan:/bitnami'
    environment:
      - NEO4J_HOST=localhost
    restart: always